### ISSUE TITLE
HTML autocomplete appearing for Markdown files

### ISSUE THREAD

**Issue by emichael** [SublimeCodeIntel/SublimeCodeIntel#471]
On the recent update, I noticed that the HTML autocomplete functionality is running for Markdown files. I don't have any user settings to map Markdown to HTML, and I can't seem to disable this without disabling HTML autocompletion entirely.

Any suggestions for a workaround would be appreciated.

**Comment by wizza-smile** [comment]
hello @emichael, are you talking about the HTML snippets? Those are not coming from SublimeCodeIntel but from Sublime directly. If you trigger your key-command for Sublimes "show_scope_name" you will see in your statusbar, that to Sublime markdown's scope is "text.html.markdown". So to Sublime its HTML, hence it will offer you it's HTML snippets.

If you are referring to something else, let me know!

**Comment by emichael** [comment]
Hi, @wizza-smile, I can't get to my computer right now, but I'll post a screencap later. But, when I remove CodeIntel, the autocomplete box goes away. In fact, if I just remove HTML from the list of CodeIntel languages, the box goes away. This makes sense since the scope is text.html.markdown. Perhaps that means that CodeIntel is treating it as HTML.

**Comment by emichael** [comment]
![sublimecodeintel - markdown](https://cloud.githubusercontent.com/assets/1312141/5989496/619bf9fc-a94f-11e4-8e8d-bcdaf3edf8f7.png)

Here's the screencap, as promised. As near as I can tell, this is a SublimeCodeIntel issue.

**Comment by wizza-smile** [comment]
While SublimeCodeIntel **might be triggering** your popup to appear, those completions displayed are **not** provided by from SublimeCodeIntel. 
Can you provide us with your 
```
  "auto_complete_selector"
  "auto_complete_triggers"
```
settings from your Sublime settings?

**Comment by emichael** [comment]
Both are the default.

    // Controls what scopes auto complete will be triggered in
    "auto_complete_selector": "source - comment",

    // Additional situations to trigger auto complete
    "auto_complete_triggers": [ {"selector": "text.html", "characters": "<"} ],

**Comment by wizza-smile** [comment]
Fine. If you would like to get a better feeling for what is going on:
Please set ` "auto_complete_selector": "source - comment, text.html.markdown" `
and remove HTML from `codeintel_enabled_languages`.
You will most likely find yourself in exactly the same situation that you are in right now. But this time SublimeCodeIntel is nowhere in sight. 

the reason is this: as soon as the completion popup opens in a scope that starts with `text.html` SublimeText will throw its HTML snippets in the mix. And since markdown *IS* HTML to Sublime... well, you see...

**Comment by emichael** [comment]
I did exactly as you suggested, and the popups were gone. No matter how I fiddled with the `auto_complete_selector` and `auto_complete_triggers`, I couldn't get the completion popups when HTML was missing from `codeintel_enabled_languages`.

**Comment by wizza-smile** [comment]
yes sorry, that is a bug in SublimeCodeIntel 2.0.7, where it is messing with your default Sublime's auto_complete. If you remove it and install `CodeCompplice` via packageControl instead (its a fork of the project), you will find it working as described. Maybe we could work on a solution for your feature request, to benefit the whole community?! 
https://github.com/spectacles/CodeComplice

**Comment by JoshCork** [comment]
Hoping to hear when there is a fix for this.  Removed HTML and HTML5 and as stated above it stopped trying to auto complete my markdown.  whew!  That was maddening!

**Comment by wizza-smile** [comment]
Actually I would totally recommend removing HTML from enabled_languages, since there are virtually no completions from SublimeCodeIntel for HTML. Sublime on the other hand offers good HTML completions ootb.

I am not sure if I understand you right, what exactly is the feature you are looking for? 

greetings

**Comment by emichael** [comment]
It's not a feature so much as a bug fix... You said that there was an issue with SublimeCodeIntel mucking with Sublime's own auto_complete settings.

**Comment by wizza-smile** [comment]
well, those bugs are fixed in CodeComplice (packagecontrol.io). I'd be interested to find out if that will give you what you want!

**Comment by marksix** [comment]
I have the same problem.

**Comment by amowu** [comment]
I have the same problem.

**Comment by ccorcos** [comment]
same problem!

**Comment by DanHulton** [comment]
To reiterate, for anyone with this problem, go and change your user settings for SublimeCodeIntel to look like:

```
{
    /*
       An array of language names which are enabled.
    */
    "codeintel_enabled_languages":
    [
       "JavaScript", "SCSS", "Python",
       "Ruby", "Python3", "XML", "Sass", "HTML5", "Perl", "CSS",
       "Twig", "Less", "Node.js", "TemplateToolkit", "PHP"
    ],
}
```

This removes "HTML" from the list of languages that SublimeIntel suggests for, which -- since Markdown is for some reason detected as HTML -- stops it from suggesting for Markdown.  You'll still get HTML suggestions, since SublimeText itself does reasonable suggestions for HTML.

**Comment by RheingoldRiver** [comment]
@DanHulton thank you so much explicitly writing out the solution, I just spent like 2 hours trying to figure this out and your commend is how I finally got it. Apparently enabled_languages overrides disabled_languages....
